spring:
  application:
    name: techtrix
      
  datasource:
    url: jdbc:mysql://localhost:3306/techtrix_db
    username: root #techtrix_user
    password: Namo@1234 #techtrix
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQLDialect

  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
      - https://crm.techtrix.in
      allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS

  mail:
    host: smtp.gmail.com
    port: 587
    username: nitis576ni@gmail.com
    password: uzma slyc uoim cckb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
logging:
  level:
    org:
      springframework:
        web: trace
    apache: trace

