server:
  port: 8080

spring:
  application:
    name: techtrix

  datasource:
    url: jdbc:mysql://mysql-3c5eae90-bopo.i.aivencloud.com:27841/tick_tool_db?useSSL=true&requireSSL=true&verifyServerCertificate=true&serverTimezone=UTC&sslMode=VERIFY_CA
    username: avnadmin
    password: AVNS_jV-6OHOWR4nwmmQvqPy
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        sslMode: VERIFY_CA
        trustCertificateKeyStoreUrl: file:/C:/certs/bopo_ca.jks
        trustCertificateKeyStorePassword: changeit
        trustCertificateKeyStoreType: JKS

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - https://crm.techtrix.in
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

  management:
    endpoints:
      jmx:
        exposure:
          include: "*"
    # metrics:
    #   export:
    #     enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nitis576ni@gmail.com
    password: uzma slyc uoim cckb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    path: /home/techtrix/app-logs
    name: TechtrixApp.log
  logback:
    rollingpolicy:
      file-name-pattern: TechtrixApp-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      total-size-cap: 50MB
      max-history: 30
      clean-history-on-start: true
  level:
    org:
      springframework:
        web: trace
    apache: trace
