server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: techtrix
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ticktool
    password: Ticket@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:3000
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

  management:
    endpoints:
      jmx:
        exposure:
          include: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    path: ./logs
    name: TechtrixApp.log
  logback:
    rollingpolicy:
      file-name-pattern: TechtrixApp-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      total-size-cap: 50MB
      max-history: 30
      clean-history-on-start: true
  level:
    org:
      springframework:
        web: trace
    apache: trace

